/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Airline;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author hetro
 */
public class Account extends javax.swing.JFrame {
    

    DefaultTreeModel model;

    /**
     * Creates new form Account
     */
    DefaultMutableTreeNode ticketRoot = new DefaultMutableTreeNode();

    public Account() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        profileName.setText(temp.tempFname + " " + temp.tempLname);
        email.setText(temp.tempEmail);
        mobile.setText(temp.tempMobile);

        try {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline", "root", "");
            Statement stm = conn.createStatement();

            ResultSet rs = stm.executeQuery("select * from ticket where mobile='"+temp.tempMobile+"'");

            while (rs.next()) {
                String Ticket = "";
                Ticket += rs.getString(3);
                Ticket += " - ";
                Ticket += rs.getString(4);
                Ticket += " - ";
                Ticket += rs.getString(7);

                DefaultMutableTreeNode t = new DefaultMutableTreeNode(Ticket);
                ticketRoot.add(t);
            }
            model = (DefaultTreeModel) jTree1.getModel();
            model.setRoot(ticketRoot);
            jTree1.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        profileName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Airline/images/new_image-removebg-preview.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(300, 550, 140, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Airline/images/Avatar.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-50, 50, 350, 240);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Click here");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 220, 60, 16);

        mobile.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        mobile.setText("9510268400");
        jPanel1.add(mobile);
        mobile.setBounds(120, 410, 250, 30);

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Logout");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(430, 10, 70, 20);

        profileName.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        profileName.setText("Het Rojivadiya");
        jPanel1.add(profileName);
        profileName.setBounds(290, 160, 180, 30);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setText("About");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 300, 130, 30);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel11.setText("Mobile :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 410, 70, 30);

        jLabel13.setText("If You want to change Profile Details");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(290, 200, 220, 16);

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel14.setText("E-mail :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 370, 70, 30);

        email.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        email.setText("hetrojivadiya999@gmail.com");
        jPanel1.add(email);
        email.setBounds(120, 370, 250, 30);

        jLabel16.setText("Your Tickets");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(40, 460, 150, 16);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("If You Want To Book New Ticket");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(100, 570, 200, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(40, 440, 340, 10);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(40, 407, 340, 3);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Profile");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(110, 10, 60, 20);

        jLabel18.setText("Contact Information");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(40, 340, 150, 16);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setScrollsOnExpand(false);
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 480, 300, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(460, 20, 500, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        AR2 a;
        try {
            a = new AR2();
            a.setVisible(true);
            dispose();
        } catch (ParseException ex) {
            Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        UpdateAccount o = new UpdateAccount();
        o.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        SkyLinePage1 n = new SkyLinePage1();
        n.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        try {
            ticketRoot = (DefaultMutableTreeNode) jTree1.getSelectionPath().getLastPathComponent();
            
            String t = ticketRoot.getUserObject().toString();
            String loc = "";
            int le = 0;
            String des = "";
            int de = 0;
            String date = "";

            for (int i = 0; i < t.length(); i++) {
                if (t.charAt(i) != ' ') {
                    loc = loc + t.charAt(i);
                    le = i;

                } else {
                    break;
                }
            }

            for (int i = le + 4; i < t.length(); i++) {
                if (t.charAt(i) != ' ') {
                    des = des + t.charAt(i);
                    de = i;

                } else {
                    break;
                }
            }
            for (int i = de + 4; i < t.length(); i++) {
                date = date + t.charAt(i);

            }

            try {
                Class.forName("com.mysql.jdbc.Driver");

                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline", "root", "");
                Statement stm = conn.createStatement();

                ResultSet rs = stm.executeQuery("select * from ticket where mobile='" + mobile.getText() + "' and location='" + loc + "' and destination='" + des + "'");
                rs.next();
                
                temp.tempFlight = rs.getString(6);
                temp.tempDate = rs.getString(7);
                temp.tempDestination = des;
                temp.tempLocation = loc;
                temp.seat = rs.getString(9);
                temp.tempTime = rs.getString(8);

                Ticket obj = new Ticket();
                obj.setVisible(true);
                dispose();

            } catch (Exception e) {
                e.printStackTrace();
            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_jTree1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Account().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel mobile;
    private javax.swing.JLabel profileName;
    // End of variables declaration//GEN-END:variables
}
