/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Airline;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author hetro
 */
public class forgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form forgotPassword
     */
    public forgotPassword() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        image();
    }

    public void image() {
        ImageIcon icon = new ImageIcon("D:\\NetBeansProjects\\JavaApplication2\\src\\Airline\\images\\button-removebg-preview.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(lable.getWidth(), lable.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        lable.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        npass = new javax.swing.JTextField();
        lable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Forget Password");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 50, 360, 50);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("New Password*");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 320, 210, 17);
        jPanel2.add(sc);
        sc.setBounds(50, 260, 310, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Enter Your username or Email*");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 140, 220, 17);
        jPanel2.add(username);
        username.setBounds(50, 170, 310, 40);

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Next");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(130, 420, 150, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("What is your favorite pet?*");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 230, 210, 17);
        jPanel2.add(npass);
        npass.setBounds(50, 350, 310, 40);

        lable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableMouseClicked(evt);
            }
        });
        jPanel2.add(lable);
        lable.setBounds(10, 10, 40, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(480, 130, 420, 490);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1380, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        if (username.getText().equals("") || sc.getText().equals("") || npass.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Fullfill All Details");
        } else {
            try {
                Class.forName("com.mysql.jdbc.Driver");

                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline", "root", "");
                Statement s = con.createStatement();

                String u = username.getText();
                String p = sc.getText();
                String np = npass.getText();

                ResultSet rs = s.executeQuery("select * from accounts where (Email='" + u + "' or Mobile='" + u + "') and Question='" + p + "'");

                if (rs.next() == false) {
                    JOptionPane.showMessageDialog(this, "Username and SecurityCode is not Match");
                } else {
                    PreparedStatement ps = con.prepareStatement("UPDATE accounts SET Password='" + np + "' WHERE (Email='" + u + "' or Mobile='" + u + "') and Question='" + p + "'");
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Password Updated Successfully");

                    SkyLinePage1 n = new SkyLinePage1();
                    n.setVisible(true);
                    dispose();
                }

                con.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

    }//GEN-LAST:event_jPanel2MouseClicked

    private void lableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableMouseClicked
        SkyLinePage1 s = new SkyLinePage1();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_lableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lable;
    private javax.swing.JTextField npass;
    private javax.swing.JTextField sc;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
