
package Airline;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author hetro
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        HolderName.setText(temp.tempHoldername);
        AccNo.setText(temp.tempAccNo);
        CVV.setText(temp.tempCVV);
        Month.setText(temp.tempMonth);
        Year.setText(temp.tempYear);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AccNo = new javax.swing.JTextField();
        CVV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        HolderName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Year = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Month = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Name Of AccountHolder*");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 150, 160, 24);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Payment details");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 90, 160, 17);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("VALID UNTIL*");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(180, 360, 110, 18);

        AccNo.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        AccNo.setForeground(new java.awt.Color(102, 102, 102));
        AccNo.setText("XXXX-XXXX-XX89");
        AccNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccNoMouseClicked(evt);
            }
        });
        AccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccNoActionPerformed(evt);
            }
        });
        jPanel2.add(AccNo);
        AccNo.setBounds(50, 290, 300, 29);

        CVV.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        CVV.setForeground(new java.awt.Color(102, 102, 102));
        CVV.setText("cvv");
        CVV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CVVMouseClicked(evt);
            }
        });
        CVV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVVActionPerformed(evt);
            }
        });
        jPanel2.add(CVV);
        CVV.setBounds(50, 390, 80, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Account Number*");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, 260, 110, 17);

        HolderName.setForeground(new java.awt.Color(102, 102, 102));
        HolderName.setText("Name...");
        HolderName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HolderNameMouseClicked(evt);
            }
        });
        jPanel2.add(HolderName);
        HolderName.setBounds(50, 190, 300, 30);

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("CVV Code*");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(50, 360, 110, 18);

        Year.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        Year.setForeground(new java.awt.Color(102, 102, 102));
        Year.setText("Year");
        Year.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YearMouseClicked(evt);
            }
        });
        Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearActionPerformed(evt);
            }
        });
        jPanel2.add(Year);
        Year.setBounds(260, 390, 50, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("/");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(240, 380, 20, 40);

        Month.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        Month.setForeground(new java.awt.Color(102, 102, 102));
        Month.setText("Month");
        Month.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MonthMouseClicked(evt);
            }
        });
        Month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthActionPerformed(evt);
            }
        });
        jPanel2.add(Month);
        Month.setBounds(180, 390, 50, 30);

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PAY");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(50, 470, 120, 40);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Airline/images/button-removebg-preview.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11);
        jLabel11.setBounds(410, 10, 60, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(280, 0, 470, 530);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Airline/images/Payment card.jpg.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 290, 190);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Airline/images/Payment card 2.jpg.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 340, 240, 190);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Airline/images/Payment 3.jpg.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 220, 240, 110);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(470, 80, 750, 530);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Airline/images/Payment .jpg.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(70, 290, 280, 200);

        jLabel14.setFont(new java.awt.Font("Segoe UI Emoji", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 255, 153));
        jLabel14.setText("ON");
        jLabel14.setToolTipText("Secure Mode ON");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(180, 270, 80, 70);

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 255, 153));
        jLabel13.setText("Secure Mode");
        jLabel13.setToolTipText("Secure Mode ON");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(60, 210, 310, 70);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1460, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccNoActionPerformed

    private void CVVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CVVActionPerformed

    private void YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearActionPerformed

    private void MonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthActionPerformed

    private void HolderNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HolderNameMouseClicked
        HolderName.setText(null);      // TODO add your handling code here:
    }//GEN-LAST:event_HolderNameMouseClicked

    private void AccNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccNoMouseClicked
        AccNo.setText(null); // TODO add your handling code here:
    }//GEN-LAST:event_AccNoMouseClicked

    private void CVVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CVVMouseClicked
        CVV.setText(null); // TODO add your handling code here:
    }//GEN-LAST:event_CVVMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        temp.tempHoldername = HolderName.getText();
        temp.tempAccNo = AccNo.getText();
        temp.tempCVV = CVV.getText();
        temp.tempMonth = Month.getText();
        temp.tempYear = Year.getText();
        SeatChoose s = new SeatChoose();
        s.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void MonthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MonthMouseClicked
        Month.setText(null);    // TODO add your handling code here:
    }//GEN-LAST:event_MonthMouseClicked

    private void YearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YearMouseClicked
        Year.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_YearMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

       
        String cvv = CVV.getText();
        int month = 0,year = 0;

        if (HolderName.getText().equals("") || AccNo.getText().equals("") || CVV.getText().equals("") || Month.getText().equals("") || Year.getText().equals("")) {
            
        } else {
            if (HolderName.getText().length() >= 5) {
                try{
                month = Integer.parseInt(Month.getText());
                year = Integer.parseInt(Year.getText());
                }
                catch(Exception e)
                 {
                      JOptionPane.showMessageDialog(this, "Please FullFill All Details");
                 }
                if ((AccNo.getText().length() >= 9 && AccNo.getText().length() <= 18 ) && (month >= 1 && month <= 12) && (year >= 2023 && year <= 2050)) {
                    if (CVV.getText().length() == 3) {
                        try {
                            Integer.parseInt(cvv);
                            temp.tempHoldername = HolderName.getText();
                            temp.tempAccNo = AccNo.getText();
                            temp.tempCVV = CVV.getText();
                            temp.tempMonth = Month.getText();
                            temp.tempYear = Year.getText();
                            JOptionPane.showMessageDialog(this, "Transaction Done Successfuly");
                            temp.main();
                            temp n=new temp();
                            Ticket t=new Ticket();
                            t.setVisible(true);
                            
                            dispose();
                            
                            
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(this, "CVV  Wrong");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "CVV is Wrong");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Something is Wrong Please Check It");
                }
            } else {
                JOptionPane.showMessageDialog(this, "HolderName is Not Match");
            }
        }
      

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccNo;
    private javax.swing.JTextField CVV;
    private javax.swing.JTextField HolderName;
    private javax.swing.JTextField Month;
    private javax.swing.JTextField Year;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
