/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Airline;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import org.apache.pdfbox.pdmodel.*;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.graphics.image.LosslessFactory;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;


/**
 *
 * @author hetro
 */
public class testImgae extends javax.swing.JFrame {

    /**
     * Creates new form testImgae
     */
    public testImgae() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        //image();
        //delete();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panel.setLayout(null);

        jLabel2.setText("Het Rojivadiya");
        panel.add(jLabel2);
        jLabel2.setBounds(400, 100, 90, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Airline/images/ticket.jpg"))); // NOI18N
        panel.add(jLabel1);
        jLabel1.setBounds(80, 80, 720, 322);

        getContentPane().add(panel);
        panel.setBounds(0, 0, 850, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void delete()
    {
        File file = new File("C:\\Users\\hetro\\OneDrive\\Documents\\NetBeansProjects\\Skyline\\src\\Airline\\document.pdf");
        file.delete();
    }
    public void image()
    {
        BufferedImage image = new BufferedImage(panel.getWidth(), panel.getHeight(), BufferedImage.TYPE_INT_RGB);

        // Create a Graphics object from the BufferedImage
        Graphics2D graphics = image.createGraphics();

        // Render the component to the BufferedImage
        panel.paint(graphics);

        // Dispose the Graphics object
        graphics.dispose();

        // Save the BufferedImage to a file
//        try {
//            ImageIO.write(image, "png", new File(""));
//            System.out.println("Image saved successfully.");
//        } catch (IOException e) {
//            e.printStackTrace();
//        }

        try {
            PDDocument document = new PDDocument();
            PDPage page = new PDPage(new PDRectangle(panel.getWidth(), panel.getHeight()));
            document.addPage(page);

            PDImageXObject pdImage = LosslessFactory.createFromImage(document, image);
            PDPageContentStream contentStream = new PDPageContentStream(document, page);
            contentStream.drawImage(pdImage, 0, 0);
            contentStream.close();

            document.save(new File("C:\\Users\\hetro\\OneDrive\\Documents\\NetBeansProjects\\Skyline\\src\\Airline\\document.pdf"));
            document.close();

            System.out.println("PDF saved successfully.");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testImgae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testImgae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testImgae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testImgae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testImgae().setVisible(true);
                
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
